basket = [["apples","bananas"],["milk","water"]]
print(basket)
print("press Enter to change the content...\n")
basket[0].insert(0,"oranges")
basket[0].append("kiwis")
basket[1].insert(0,"coffee")
basket[1].remove("water")
basket[1].append("tea")
basket.append([1,2,3])
print (basket)
